[
  {
    "py/object": "objects.Link",
    "src": {
      "py/object": "objects.Exception",
      "type": "org.apache.hadoop.hive.ql.parse.ParseException",
      "method": "org.apache.hadoop.hive.ql.parse.ParseDriver/parse:125",
      "message": "null"
    },
    "dst": {
      "py/object": "objects.Exception",
      "type": "org.apache.hadoop.hive.ql.processors.CommandProcessorException",
      "method": "org.apache.hadoop.hive.ql.DriverUtils/createProcessorException:181",
      "message": "FAILED: ParseException null"
    }
  },
  {
    "py/object": "objects.Link",
    "src": {
      "py/object": "objects.Exception",
      "type": "java.lang.RuntimeException",
      "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
      "message": "cannot open scope"
    },
    "dst": {
      "py/object": "objects.Exception",
      "type": "java.lang.RuntimeException",
      "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
      "message": "cannot open scope"
    }
  },
  {
    "py/object": "objects.Link",
    "src": {
      "py/object": "objects.Exception",
      "type": "org.apache.hadoop.hive.ql.processors.CommandProcessorException",
      "method": "org.apache.hadoop.hive.ql.DriverUtils/createProcessorException:181",
      "message": "FAILED: RuntimeException cannot open scope"
    },
    "dst": {
      "py/object": "objects.Exception",
      "type": "java.lang.RuntimeException",
      "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
      "message": "cannot open scope"
    }
  },
  {
    "py/object": "objects.Link",
    "src": {
      "py/object": "objects.Exception",
      "type": "java.lang.RuntimeException",
      "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
      "message": "cannot open scope"
    },
    "dst": {
      "py/object": "objects.Exception",
      "type": "org.apache.hadoop.hive.ql.processors.CommandProcessorException",
      "method": "org.apache.hadoop.hive.ql.DriverUtils/createProcessorException:181",
      "message": "FAILED: RuntimeException cannot open scope"
    }
  },
  {
    "py/object": "objects.Link",
    "src": {
      "py/object": "objects.Exception",
      "type": "org.apache.hadoop.hive.ql.parse.ParseException",
      "method": "org.apache.hadoop.hive.ql.parse.ParseDriver/parse:125",
      "message": "null"
    },
    "dst": {
      "py/object": "objects.Exception",
      "type": "java.lang.RuntimeException",
      "method": "org.apache.hadoop.hive.common.metrics.metrics2.CodahaleMetrics$CodahaleMetricsScope/open:126",
      "message": "cannot open scope"
    }
  }
]